// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.24.4
// source: pkg/logger/grpc/simulated_service.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SimulatedService_SayHello_FullMethodName = "/handlers.SimulatedService/SayHello"
)

// SimulatedServiceClient is the client API for SimulatedService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service definition
type SimulatedServiceClient interface {
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error)
}

type simulatedServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSimulatedServiceClient(cc grpc.ClientConnInterface) SimulatedServiceClient {
	return &simulatedServiceClient{cc}
}

func (c *simulatedServiceClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HelloResponse)
	err := c.cc.Invoke(ctx, SimulatedService_SayHello_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SimulatedServiceServer is the server API for SimulatedService service.
// All implementations must embed UnimplementedSimulatedServiceServer
// for forward compatibility.
//
// Service definition
type SimulatedServiceServer interface {
	SayHello(context.Context, *HelloRequest) (*HelloResponse, error)
	mustEmbedUnimplementedSimulatedServiceServer()
}

// UnimplementedSimulatedServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSimulatedServiceServer struct{}

func (UnimplementedSimulatedServiceServer) SayHello(context.Context, *HelloRequest) (*HelloResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedSimulatedServiceServer) mustEmbedUnimplementedSimulatedServiceServer() {}
func (UnimplementedSimulatedServiceServer) testEmbeddedByValue()                          {}

// UnsafeSimulatedServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SimulatedServiceServer will
// result in compilation errors.
type UnsafeSimulatedServiceServer interface {
	mustEmbedUnimplementedSimulatedServiceServer()
}

func RegisterSimulatedServiceServer(s grpc.ServiceRegistrar, srv SimulatedServiceServer) {
	// If the following call pancis, it indicates UnimplementedSimulatedServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SimulatedService_ServiceDesc, srv)
}

func _SimulatedService_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SimulatedServiceServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SimulatedService_SayHello_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SimulatedServiceServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SimulatedService_ServiceDesc is the grpc.ServiceDesc for SimulatedService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SimulatedService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "handlers.SimulatedService",
	HandlerType: (*SimulatedServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _SimulatedService_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/logger/grpc/simulated_service.proto",
}
